### ISSUE TITLE
Add all ping method to numerai DataLoader

### ISSUE THREAD

**Issue by parkerburchett** [parkerburchett/Numerai#5]
Ping Tournament Data
Ping Training Data

**Comment by parkerburchett** [comment]
Ping Tournament Data does not properly strip the "era" characters from the era column. I don't think it will change anything since you are only predicting on the features for the final model.

**Comment by parkerburchett** [comment]
```
tournament_df = dl.ping_tournament_data() 
```
Gives warning

```
Traceback (most recent call last):
  File "/content/Numerai/SimpleScoreCalculator.py", line 363, in ping_tournament_data
    valid_df["era"] = valid_df["era"].apply(lambda x: int(x[3:])) # strip the word 'era' from the era column and cast as an int
  File "/usr/local/lib/python3.7/dist-packages/pandas/core/series.py", line 4213, in apply
    mapped = lib.map_infer(values, f, convert=convert_dtype)
  File "pandas/_libs/lib.pyx", line 2403, in pandas._libs.lib.map_infer
  File "/content/Numerai/SimpleScoreCalculator.py", line 363, in <lambda>
    valid_df["era"] = valid_df["era"].apply(lambda x: int(x[3:])) # strip the word 'era' from the era column and cast as an int
ValueError: invalid literal for int() with base 10: 'X'
CPU times: user 3min 59s, sys: 16.4 s, total: 4min 15s
Wall time: 4min 42s
```
